=head1 NAME

Tree::Serial - Perl module for deserializing lists of strings into tree-like structures and vice versa

=head1 SYNOPSIS

This is a stub.

=head1 DESCRIPTION

This is a stub.

=head1 ATTRIBUTES

=head2 separator

=head2 degree

=head2 traversal

    my $ts = Tree::Serial->new({traversal => 1});

Can be 0 (meaning pre-order), 1 (meaning in-order), or 2 (meaning post-order). It will modify the behavior of the list-of-lists (de)serialization functions accordingly.

=head1 METHODS

=head1 INSTALLATION

Using L<cpanm|https://metacpan.org/dist/App-cpanminus/view/bin/cpanm>: clone this repo, C<cd> into it, and then:

    $ cpanm .

Manual install:

    $ perl Makefile.PL
    $ make
    $ make install


=cut

