=head1 NAME

Tree::Serial - Perl module for deserializing lists of strings into tree-like structures and vice versa

=head1 SYNOPSIS

This is a stub.

=head1 DESCRIPTION

This is a stub.

=head1 ATTRIBUTES

=head2 separator

=head2 degree

=head2 traversal

=head1 METHODS

=head1 INSTALLATION

Using L<cpanm|https://metacpan.org/dist/App-cpanminus/view/bin/cpanm>: clone this repo, C<cd> into it, and then:

    $ cpanm .

Manual install:

    $ perl Makefile.PL
    $ make
    $ make install


=cut

